##########
### AI ###
##########

### Get AI title suggestions

POST http://localhost:7071/api/ai-title HTTP/1.1
content-type: application/json

{
  "token": "<github token>",
  "title": "How to get started?",
  "nrOfCharacters": 60
}

### Get AI description suggestions

POST http://localhost:7071/api/ai/description HTTP/1.1

{
  "token": "<github token>",
  "title": "How to get started?",
  "content": "This is a test content",
  "nrOfCharacters": 160
}

### Get AI taxonomy suggestions

POST http://localhost:7071/api/ai/taxonomy HTTP/1.1

{
  "token": "<github token>",
  "title": "How to get started?",
  "description": "Learn how to get started and succeed with our helpful tips and advice. Discover the best ways to begin your journey towards success.",
  "taxonomy": ["getting-started", "tips", "advice"],
  "type": "tags"
}

### Get AI taxonomy suggestions

POST http://localhost:7071/api/ai/title HTTP/1.1

{
  "token": "<github token>",
  "title": "How to get started?",
  "nrOfCharacters": 60
}

#############
### Stars ###
#############

### Get stars

GET http://localhost:7071/api/stars HTTP/1.1

##################
### Supporters ###
##################

### Check if user is a supporter

GET http://localhost:7071/api/backers?backer=estruyf HTTP/1.1

### Check by using the token

POST http://localhost:7071/api/v2/backers HTTP/1.1
content-type: application/json

{
  "token": "<github token>"
}

### Get sponsors

GET http://localhost:7071/api/sponsors HTTP/1.1

### Get sponsors image

GET http://localhost:7071/api/img-sponsors HTTP/1.1

########################
### Mendable Chatbot ###
########################

### Init

GET http://localhost:7071/api/ai-init HTTP/1.1

### Chat

POST http://localhost:7071/api/ai-chat HTTP/1.1
content-type: application/json

{
  "chatId": "2436209",
  "question": "How to get started?"
}

### Feedback

POST http://localhost:7071/api/ai-feedback HTTP/1.1
content-type: application/json

{
  "answerId": "4527447",
  "vote": 1
}

### AI Title

POST http://localhost:7071/api/ai-feedback HTTP/1.1
content-type: application/json

{
  "answerId": "4527447",
  "vote": 1
}